---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: {{ include "tf-module.fullname" . }}
spec:
  interval: 24h0m0s
  ref:
    commit: {{ .Values.hash }}
  url: {{ .Values.url }}
---
apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
  name: {{ include "tf-module.fullname" . }}
spec:
  approvePlan: auto
  interval: 24h0m0s
  path: {{ .Values.path }}
  sourceRef:
    kind: GitRepository
    name: {{ include "tf-module.fullname" . }}
  vars:
  - name: admin_username
    value: postgres
  - name: database
    value: my-app
  - name: host
    value: postgresql.infrastructure.svc.cluster.local
  - name: user
    value: my-app
  - name: admin_password
    value: super-secret-password
  writeOutputsToSecret:
    name: {{ include "tf-module.fullname" . }}-output
