---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: {{ template "robustName" .Release.Name }}
  namespace: flux-system
spec:
  interval: 24h0m0s
  ref:
    {{- if .Values.tfModule.tag }}
    tag: {{ .Values.tfModule.tag }}
    {{- end }}
    {{- if .Values.tfModule.branch }}
    branch: {{ .Values.tfModule.branch }}
    {{- end }}
    {{- if .Values.tfModule.hash }}
    commit: {{ .Values.tfModule.hash }}
    {{- end }}
  url: {{ .Values.tfModule.url }}
---
apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
  name: {{ template "robustName" .Release.Name }}
  namespace: flux-system
  annotations:
    gimlet.io/belongs-to: {{ .Values.app }}
spec:
  approvePlan: auto
  interval: 24h0m0s
  path: {{ .Values.tfModule.path }}
  sourceRef:
    kind: GitRepository
    name: {{ template "robustName" .Release.Name }}
  destroyResourcesOnDeletion: false
  disableDriftDetection: true
  storeReadablePlan: human
  retryInterval: 24h
  vars:
  - name: database
    value: {{ .Values.database }}
  - name: username
    value: {{ .Values.username }}
  varsFrom:
    - kind: Secret
      name: {{ template "robustName" .Release.Name }}
    - kind: Secret
      name: postgresql-admin-credentials
  writeOutputsToSecret:
    name: {{ include "tf-module.fullname" . }}-output
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ template "robustName" .Release.Name }}
  namespace: flux-system
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
spec:
  encryptedData:
    password: {{ .Values.password }}
---
apiVersion: v1
kind: Secret
metadata:
  name: postgresql-admin-credentials
  namespace: flux-system
type: Opaque
stringData:
  host: postgresql.infrastructure.svc.cluster.local
  admin_username: postgres
  admin_password: sprscrtpsswrd
